### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by CorySanin** [oslerw/quipbot#1]
When I run bundle exec ./quipbot.rb (in the correct directory) I get "bundler: command not found: ./quipbot.rb
Install missing gem executables with `bundle install`"

Running that command solves nothing. My only guess is perhaps I don't have geckodriver installed correctly. What do I need to do to install geckodriver (on Ubuntu)?

**Comment by keeakita** [comment]
First you'll need to install bundler: `gem install bundler`. If you get an error here, you can try it with `sudo`, but I don't recommend it. It's worth taking the time to set up either [rbenv](https://github.com/rbenv/rbenv) or [rvm](https://rvm.io/) so that you can install new versions of ruby and manage gems without needing root permissions. Once you've installed bundler, things should work.

As far as geckodriver, I've never actually installed it on Ubuntu, I've only tested this on Arch. Honestly it's been a while since I've touched this code. You can try grabbing a binary from the geckodriver release page: https://github.com/mozilla/geckodriver/releases/tag/v0.15.0

**Comment by CorySanin** [comment]
I see you've made some updates to the project. That's great!

I'm still having issues. I never got the old version to work, and by the time you replied I had given up. However, driven by my desire to see a Quiplash bot work, I decided to give it another shot.

This time, I managed to finally get beyond the "command not found" error (after over an hour and a half of tinkering). Now I'm at what seems to be the final hurdle; how do I create the necessary model.mp.gz file for the bot to function? I don't see anything in your instructions mentioning it. I'm clueless. Thanks!

**Comment by keeakita** [comment]
Sorry about that, I never actually wrote those docs (or exposed that code in any way, I've just been calling it from a debugger).

I've added a script that should get you started, and some instructions on running it. Let me know if you run into any issues with it.
